### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [NDevTK/PyLock#1]
Hello Sir Thank you for the best script but are you this script will protect my code from stolen

**Comment by jamesatjaminit** [comment]
If you're asking whether the script is definitely secure it says on [L34 of the compile.py](https://github.com/NDevTK/PyLock/blob/master/Main.py#L34) that it shouldn't be trusted to be secure.

**Comment by NDevTK** [comment]
Hi @VoipSip,
The input script is encrypted with a key from Scrypt using the password provided and a salt from os.urandom(40).
With the password the script can be decrypted back to its original state with basic changes to PyLock.
https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet

**Comment by VoipSip** [comment]
File "MGKK.py", line 36
    kdf = Scrypt(salt=53e7aaf9f68cab6118430379ef22499b41fac0095fa13c751c7227b37c39d7fac8eb4cdb810e6823,length
=32,n=2**14,r=8,p=1,backend=default_backend())
                                                                                                     ^
SyntaxError: invalid syntax

there is error

**Comment by NDevTK** [comment]
@VoipSip there is no kdf  for me on line 39.
I think it should be like `salt=b'blah'` instead of `salt=blah`
Have you changed the code?

**Comment by VoipSip** [comment]
no never i using your code and he is good code but i'm Searching for PyLock make my  code safe can't decoded

**Comment by NDevTK** [comment]
I dont know how to reproduce the error.
Is there any information that might help me?

**Comment by VoipSip** [comment]
yes sir can you help me please for script to cracking this page like this but i will put big much 

http://185.151.117.198:8080/admin/config.php 

username : admin
password : adrian

some have port like this ip some not have also some https and some http 

i want great script  for cracking login page for this type with multi threading and multiprocessing

thank you

**Comment by NDevTK** [comment]
Unrelated
